<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="netstandard">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="mscorlib">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/mscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/System.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/System.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Main">
      <HintPath>/home/astra/vint2/gamez/steamapps/common/112 Operator/Operator 112_Data/Managed/Main.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
